/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fse.test;

import java.time.LocalDate;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author karlk
 */
public class FseKundenanfrage extends javax.swing.JFrame {

    /**
     * Creates new form FseKundenanfrage
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public FseKundenanfrage() 
       throws SQLException, ClassNotFoundException  
    {
        initComponents();
       
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKdNr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMatNr = new javax.swing.JTextField();
        txtMenge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtWuTermin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSpeichern = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KundenNummer");

        jLabel2.setText("Menge");

        jLabel3.setText("Wunschtermin");

        btnSpeichern.setText("Speichern");
        btnSpeichern.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
try {         
       btnSpeichernMouseClicked(evt); }
catch (Exception e) {System.out.println(e);}
            }
        });

        jLabel4.setText("ArtikelNummer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKdNr)
                    .addComponent(txtMatNr)
                    .addComponent(txtWuTermin, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txtMenge))
                .addGap(71, 71, 71)
                .addComponent(btnSpeichern)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKdNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMatNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWuTermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnSpeichern))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
 /*   
    private void btnSpeichernMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSpeichernMouseClicked
*/
        
    private void btnSpeichernMouseClicked(java.awt.event.MouseEvent evt) 
        throws SQLException, ClassNotFoundException  
    {
    // nur eine Dummy-Aenderung fuer Rep-Test
        
        KdAnfPos position = new KdAnfPos();
        KundenAnfrage kdAnf = new KundenAnfrage();
        
        position.matNr = "222";
     // position.matNr = txtMatNr.getText();
        position.menge = 333.0;
     // position.menge = Double.parseDouble (txtMenge.getText());
        position.kdAnfPosID = KdAnfPos.anfPosCount;
                
        kdAnf.kdNr  = "122";
     // kdAnf.kdNr  = txtKdNr.getText();
        kdAnf.wunschTermin = LocalDate.now();
     // kdAnf.wunschTermin = LocalDate.parse(txtWuTermin.getText());
        kdAnf.anfrageId = KundenAnfrage.anfrageCount;
        
     //   txtWuTermin.setText (LocalDate.now().toString());
        
        System.out.println();
        System.out.println(kdAnf.anfrageId + " " + position.kdAnfPosID + " " + position.matNr + " " + kdAnf.wunschTermin);
        
        Class.forName("com.mysql.cj.jdbc.Driver");  
       
      try {
        Connection con=DriverManager.getConnection(  
           "jdbc:mysql://localhost:3306/db_10_1","root","Kurbel204");  
               
        Statement stmt = con.createStatement();
        boolean typeOfSql = stmt.execute("insert into anfrage values (12, 23, '2024-07-07');");
     // boolean typeOfSql = stmt.execute("insert into anfrage values (kdAnf.anfrageId, kdAnf.kdNr, kdAnf.wunschTermin);");
        stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from anfrage;");
        
        while (rs.next()) {
            System.out.println(rs.getString(1) + " " + rs.getString(2) + " " + rs.getString(3));
        }
        con.close();
      } 
      catch (Exception e) { 
          System.out.println(e);
      }
        
    }//GEN-LAST:event_btnSpeichernMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()  {
            public void run() {
                try {
                    new FseKundenanfrage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FseKundenanfrage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FseKundenanfrage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }) ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpeichern;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtKdNr;
    private javax.swing.JTextField txtMatNr;
    private javax.swing.JTextField txtMenge;
    private javax.swing.JTextField txtWuTermin;
    // End of variables declaration//GEN-END:variables
}
